### ISSUE TITLE
cabal2arch generates bogus PKGUBILD for haskell-platform

### ISSUE THREAD

**Issue by peti** [archhaskell/cabal2arch#15]
The haskell-platform package is not actually listed on Hackage. Consequently, the homepage URL auto-generated by cabal2arch is incorrect.

**Comment by magthe** [comment]
Maybe it would be better to use the _homepage_ property from the CABAL file, if it exists?

**Comment by peti** [comment]
In case of haskell-platform, that is definitely a good choice. I'm not so sure about other packages. The homepage URL on hackage.haskell.org is going to be stable until the end of time. The same can probably not be said about the URLs that people write into their cabal files. Anyway, if the author of the package says that his homepage is at XYZ, then it can't be wrong for us to link to XYZ. All things considered, I'm in favor of making that change.
