### ISSUE TITLE
cabal2arch can't deal with "backtick" in package description

### ISSUE THREAD

**Issue by peti** [archhaskell/cabal2arch#17]
The "vect-opengl" package uses the backtick character ("`") in it's package description string. This causes cabal2arch to fail. Arguably, failure is not completely bad on this occassion, because it would be even worse if the backtick would be passed on to the PKGBUILD unquoted.

**Comment by remyoudompheng** [comment]
I pushed a commit to properly escape characters in $pkgdesc (I didn't feel the need to use the escaping function for other variables).

**Comment by peti** [comment]
I saw your commit. Thank you very much!
