### ISSUE TITLE
cabal2arch should remove line feeds from $pkgdesc

### ISSUE THREAD

**Issue by peti** [archhaskell/cabal2arch#18]
The package "sifflet-lib" breaks its "synopsis" over multiple lines, and cabal2arch retains that formatting in the generated PKGBUILD. That's probably not a good idea. IMHO, line feeds should be replaced by a blank in that context.

**Comment by remyoudompheng** [comment]
I've changed how special characters to reflect this. Along the way I've chosen to replace any backquotes or double quotes by single quotes instead of escaping them with backslashes.

**Comment by peti** [comment]
Why do you think that those additional rewrites should be done? 

Personally, I'm not so sure that those re-writes are a good idea. It feels inappropriate for us to mess with the package author's spelling, especially since there is no technical reason to do so.
