### ISSUE TITLE
cabal2arch creates bad PKGBUILD for cabal2arch

### ISSUE THREAD

**Issue by magthe** [archhaskell/cabal2arch#20]
`cabal2arch` (the binary) tries to load two files, `ghc-provides.txt` and `library-providers.txt`.  These two files are installed by _archlinux_ (the package).  This means that the `PKGBUILD` for _cabal2arch_ can't `makedepend` on _archlinux_ but instead has to `depend` on it.  In other words, since _archlinux_ contain data files the basic assumption that executables only need to `makedepend` on all libraries is wrong for executables that use _archlinux_.

I think there are two solutions to this:
1. Move the two data files to _cabal2arch_, that's where the function for loading them is so that's where they belong.
2. Remove the data files from _archlinux_ completely and make `cabal2arch` always load them from a URL.  (Or at least make it load them from a URL by default, this might make more sense from a developer and testing perspective.)

I would prefer the second solution.

**Comment by magthe** [comment]
I should probably add that the two solutions are specific to _cabal2arch_.  In the long run we need to address the more general problem of libraries having datafiles.

**Comment by peti** [comment]
As a quick-fix, I've uploaded a new version of cabal2arch to AUR and kiwilight.com that declares a run-time dependency on haskell-archlinux. The PKGBUILD was hand-edited, though, so this is really a hack.

**Comment by magthe** [comment]
Remy, I think this can be closed, right?
