### ISSUE TITLE
failing to configure  

### ISSUE THREAD

**Issue by pintjuk** [archhaskell/cabal2arch#30]
i get this

```
   Configuring cabal2arch-1.2...
   Setup.lhs: At least the following dependencies are missing:
   cmdargs -any, mtl -any
```

**Comment by magthe** [comment]
That would most likely be caused by you not having `cmdargs` and `mtl` installed.  Please install them and try to configure again.

Please also note that `cabal2arch` is unmaintained.  We have moved on from it a long time ago.  If you find it useful I'll be happy to hand over maintenance to you.

**Comment by Profpatsch** [comment]
@magthe Would be cool if you could mark it deprecated in the readme with a more current alternative. That saves maintainers time searching for The Tool One Wants to Use.

After reading this I assume [cblrepo](https://github.com/magthe/cblrepo) is the way to go, right?
